# Indexing in Numpy Array

In [1]:
# Generate a random 5*4 array will numbers between 10 and 100.
import numpy as np
arr=np.random.randint(10,100,(5,4))
print(arr)

[[42 35 70 84]
 [90 12 14 17]
 [29 94 89 71]
 [34 23 98 81]
 [55 86 33 92]]


In [2]:
# First row
print(arr[0])
# Last row
print(arr[-1])
# Last element
print(arr[-1][-1])
print(arr[-1,-1]) # We can also use ',' to access an element in a 2-D matrix.
# Array element distribution.
print(arr.shape)

[42 35 70 84]
[55 86 33 92]
92
92
(5, 4)


In [3]:
# Array Slicing.
# arr[startRowIdx: endRowIdx+1 , startColIdx: endColIdx+1]
print(arr[2:5,1:4])

[[94 89 71]
 [23 98 81]
 [86 33 92]]


In [4]:
# Masking.
mask=arr>50
print(mask)

[[False False  True  True]
 [ True False False False]
 [False  True  True  True]
 [False False  True  True]
 [ True  True False  True]]


In [5]:
# Number of elements greater than 50. All true value will be added and true will be considered as 1.
print(np.sum(mask))

11


In [6]:
# Get all values greater than 50.
print(arr[mask])

[70 84 90 94 89 71 98 81 55 86 92]


In [7]:
# Make the elements from 3rd row, 3rd col to the end 0.
arr[2: ,2: ]=0
print(arr)

[[42 35 70 84]
 [90 12 14 17]
 [29 94  0  0]
 [34 23  0  0]
 [55 86  0  0]]


# Basic Operations in Arrays

In [8]:
a=np.array([10,20,30,40])
b=np.arange(1,5)
# These operations happen element-wise. These are called element-wise operators.
print(a+b)
print(a-b)
print(a*b)
print(b**2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[ 1  4  9 16]


In [9]:
# Mask.
print(a>15)

[False  True  True  True]


In [10]:
# Take log() of all the elements of the Array b.
print(np.log(b))
# Take sin() of all the elements of the Array a.
print(np.sin(a))

[0.         0.69314718 1.09861229 1.38629436]
[-0.54402111  0.91294525 -0.98803162  0.74511316]


#  Matrix Product
    Used heavily in Linear Algebra [Matrices can only be multiplied if the number of cols of first matrix is 
    same as the number of rows of the second matrix].

In [11]:
A=np.random.randint(0,5,(3,4))
B=np.random.randint(0,5,(4,2))

In [12]:
# To multiply two matrices we use '.' It is also known as the Dot product.
print(np.dot(A,B))

[[ 7  9]
 [14 11]
 [11  4]]


In [13]:
A=np.arange(0,24)
print(A.shape)
print(A)
# Reshape the Array A.
A=A.reshape(6,4)
print(A.shape)
print(A)

(24,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(6, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [15]:
np.sum(A)

276

In [16]:
np.max(A)

23

In [17]:
np.min(A)

0

In [18]:
# Mean of the Array A.
np.mean(A)

11.5

In [19]:
# Standard Deviation of the elements.
np.std(A)

6.922186552431729

In [20]:
# Sum of each column.
print(np.sum(A,axis=0))
# Sum of each row.
print(np.sum(A,axis=1))
# Mean of each row
print(np.mean(A,axis=1))

[60 66 72 78]
[ 6 22 38 54 70 86]
[ 1.5  5.5  9.5 13.5 17.5 21.5]


# Shape Manipulation

In [21]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
# This will compress the array A into a 1-D array.
A=A.flatten()
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [25]:
# Change the shape of the array to 6*4
A=A.reshape(6,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [26]:
# Take the transpose the matrix.
print(A.T)

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


# Stacking the array
    - Merging two arrays into one.
    - There are two types of stacking vstack and hstack. 
    hstack is horizontal stacking and vstack is vertical stacking.

In [28]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))

In [29]:
print(a)
print(b)

[[1 5]
 [9 2]]
[[7 5]
 [5 2]]


In [33]:
c=np.hstack((a,b))
print(c)
print(c.shape)

[[1 5 7 5]
 [9 2 5 2]]
(2, 4)


In [34]:
c=np.vstack((a,b))
print(c)
print(c.shape)

[[1 5]
 [9 2]
 [7 5]
 [5 2]]
(4, 2)


# Broadcasting
    -First rule of numpy:2 arraysw can perform operations only if they are in the same shape.
    -But broadcasting can let two arrays of different shapes do some operations.
        -A small array will repeat itself and convert to same shape as of another array.

In [35]:
A=np.random.randint(0,10,(3,3))
a=np.array([[1,2,3]])

In [43]:
print(A.shape,a.shape)
print(A)
print()
print(a)

(3, 3) (1, 3)
[[5 4 6]
 [5 7 2]
 [1 0 1]]

[[1 2 3]]


In [42]:
# If the two arrays don't have the same shape then the smaller array will convert itself into the size of the 
# bigger array.
# Now, a becomes [[1,2,3],[1,2,3],[1,2,3]].
# This property of numpy is called Broadcasting.
print(A+a)
print()
print(A+a.T)
print()
print(A+4)

[[6 6 9]
 [6 9 5]
 [2 2 4]]

[[6 5 7]
 [7 9 4]
 [4 3 4]]

[[ 9  8 10]
 [ 9 11  6]
 [ 5  4  5]]


# Vectorization
    - Property of Numpy to perform operations on Arrays.

In [44]:
p1=np.array([1,2])
p2=np.array([5,5])

In [48]:
# This calculates the eucilidian distance between two points.
def distance(p1,p2):
    return np.sqrt(np.sum((p1-p2)**2))

print(distance(p1,p2))

5.0
